// jwt
exports.drecjwt = {
        JWT_SECRET: "Encrypted secret here",
        JWT_ACCESS_EXPIRATION_MINUTES: 180,
        JWT_REFRESH_EXPIRATION_MINUTES: 180,
        JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10,
        JWT_RESET_PATTERN_EXPIRATION_MINUTES: 10,
        JWT_REFRESH_EXPIRATION_DAYS: 10,
        JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10
    }
